<div class="navbar ">
    <div class="navbar-inner">
        <div class="container-fluid">
            <span class="brand">Generate Code</span>
            <div class="nav-collapse">
              <?php
//                   echo $this->navigation()->menu()->setPartial('_nav.phtml')->render();
//                  / echo $this->loggedInAs();
              ?>
            </div>
        </div>
    </div>
</div>
