<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- add title for page at here -->
<title>Test</title>

<script src="/scripts/jquery.js" type="text/javascript"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>

<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/themes/base/jquery-ui.css" type="text/css" media="all" />

<link href="/scripts/twitter/css/bootstrap.css" rel="stylesheet" type="text/css" />

<link href="/styles/main.css" rel="stylesheet" type="text/css" />

<script src="/scripts/twitter/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/scripts/scripts.js" type="text/javascript"></script>

</script>
</head>
<body>
<div class="row-fluid show-grid">

  <div class="span12">
  <?php echo $this->render("header.phtml"); ?>
  </div>
</div>

  <?php  echo $this->layout()->content ?>


<div class="row-fluid  show-grid">
  <div class="span12">
  <?php  echo $this->render("footer.phtml"); ?>
  </div>
</div>


</body>
</html>
